import type { BaseConfig } from "../../BaseConfig";
import { Dialogue } from "../uv-shared-module/Dialogue";
export declare class ShareDialogue<T extends BaseConfig["modules"]["shareDialogue"]> extends Dialogue<T> {
    copyToClipboardEnabled: boolean;
    $urlInput: JQuery;
    $urlSection: JQuery;
    isShareViewVisible: boolean;
    $manifestInput: JQuery;
    $manifestSection: JQuery;
    shareManifestsEnabled: boolean;
    $iiifButton: JQuery;
    embedCode: string;
    $embedCode: JQuery;
    $embedSection: JQuery;
    isEmbedViewVisible: boolean;
    $customSize: JQuery;
    $customSizeDropDown: JQuery;
    $size: JQuery;
    $widthInput: JQuery;
    $x: JQuery;
    $heightInput: JQuery;
    $termsOfUseButton: JQuery;
    aspectRatio: number;
    currentHeight: number;
    currentWidth: number;
    maxWidth: number;
    maxHeight: number;
    minWidth: number;
    minHeight: number;
    constructor($element: JQuery);
    create(): void;
    open(triggerButton?: HTMLElement): void;
    getShareUrl(): string | null;
    isShareAvailable(): boolean;
    addCopyButton($input: any): void;
    update(): void;
    updateShareOptions(): void;
    getSelectedSize(): JQuery;
    updateWidthRatio(): void;
    updateHeightRatio(): void;
    updateTermsOfUseButton(): void;
    close(): void;
    resize(): void;
}
