import React from "react";
import { Canvas, Size, IExternalResourceData, Sequence, Manifest } from "manifesto.js";
import { DownloadOption } from "../../modules/uv-shared-module/DownloadOption";
import { CroppedImageDimensions } from "./CroppedImageDimensions";
declare const DownloadDialogue: ({ canvases, confinedImageSize, content, downloadCurrentViewEnabled, downloadWholeImageHighResEnabled, downloadWholeImageLowResEnabled, getConfinedImageDimensions, getConfinedImageUri, getCroppedImageDimensions, locale, manifest, maxImageWidth, minImageWidth, mediaDownloadEnabled, onClose, onDownload, onDownloadCurrentView, onDownloadSelection, onShowTermsOfUse, open, paged, parent, resources, requiredStatement, rotation, selectionEnabled, sequence, termsOfUseEnabled, triggerButton, }: {
    canvases: Canvas[];
    confinedImageSize: number;
    content: {
        [key: string]: string;
    };
    downloadCurrentViewEnabled: boolean;
    downloadWholeImageHighResEnabled: boolean;
    downloadWholeImageLowResEnabled: boolean;
    getConfinedImageDimensions: (canvas: Canvas) => Size | null;
    getConfinedImageUri: (canvas: Canvas) => string | null;
    getCroppedImageDimensions: (canvas: Canvas) => CroppedImageDimensions | null;
    locale: string;
    manifest: Manifest;
    maxImageWidth: number;
    minImageWidth: number;
    mediaDownloadEnabled: boolean;
    onClose: () => void;
    onDownload: (type: DownloadOption, label: string) => void;
    onDownloadCurrentView: (canvas: Canvas) => void;
    onDownloadSelection: () => void;
    onShowTermsOfUse: () => void;
    open: boolean;
    paged: boolean;
    parent: HTMLElement;
    resources: IExternalResourceData[] | null;
    requiredStatement: string | null | undefined;
    rotation: number;
    selectionEnabled: boolean;
    sequence: Sequence;
    termsOfUseEnabled: boolean;
    triggerButton: HTMLElement;
}) => React.JSX.Element | null;
export default DownloadDialogue;
