import { AnnotationGroup, AnnotationRect } from "@iiif/manifold";
import { IExternalResource, IExternalResourceData } from "manifesto.js";
import { XYWHFragment } from "../uv-shared-module/XYWHFragment";
import { CenterPanel } from "../uv-shared-module/CenterPanel";
import OpenSeadragon from "openseadragon";
import "@openseadragon-imaging/openseadragon-viewerinputhook";
import { Config } from "../../extensions/uv-openseadragon-extension/config/Config";
interface AnnotationOverlayRect extends OpenSeadragon.Rect {
    canvasIndex: number;
    resultIndex: number;
    chars: string;
}
export declare class OpenSeadragonCenterPanel extends CenterPanel<Config["modules"]["openSeadragonCenterPanel"]> {
    controlsVisible: boolean;
    currentAnnotationRect: AnnotationRect;
    currentBounds: XYWHFragment | null;
    handler: any;
    initialBounds: XYWHFragment | null;
    initialRotation: any;
    isCreated: boolean;
    isLoaded: boolean;
    isFirstLoad: boolean;
    items: any[];
    navigatedFromSearch: boolean;
    nextButtonEnabled: boolean;
    prevButtonEnabled: boolean;
    previousAnnotationRect: AnnotationRect;
    userData: any;
    viewer: any;
    viewerId: string;
    showAdjustImageButton: boolean;
    $canvas: JQuery;
    $goHomeButton: JQuery;
    $navigator: JQuery;
    $nextButton: JQuery;
    $prevButton: JQuery;
    $rotateButton: JQuery;
    $spinner: JQuery;
    $viewer: JQuery;
    $viewportNavButtonsContainer: JQuery;
    $viewportNavButtons: JQuery;
    $zoomInButton: JQuery;
    $zoomOutButton: JQuery;
    $adjustImageButton: JQuery;
    $choiceSwitchButton: JQuery;
    constructor($element: JQuery);
    create(): void;
    whenCreated(cb: () => void): void;
    whenLoaded(cb: () => void): void;
    zoomIn(): void;
    zoomOut(): void;
    rotateRight(): void;
    updateResponsiveView(): void;
    createUI(): Promise<void>;
    createNavigationButtons(): void;
    createChoiceSwitch(): void;
    getGirderTileSource(): Promise<any>;
    openMedia(resources?: IExternalResource[]): Promise<void>;
    getPagePositions(resources: IExternalResourceData[]): IExternalResourceData[];
    openPagesHandler(): void;
    private resizeNavigatorForContinuous;
    zoomToInitialAnnotation(): void;
    overlayAnnotations(): void;
    updateBounds(): void;
    goHome(): void;
    disablePrevButton(): void;
    enablePrevButton(): void;
    hidePrevButton(): void;
    showPrevButton(): void;
    disableNextButton(): void;
    enableNextButton(): void;
    hideNextButton(): void;
    showNextButton(): void;
    fitToBounds(bounds: XYWHFragment, immediate?: boolean): void;
    getCroppedImageBounds(): string | null;
    getViewportBounds(): XYWHFragment | null;
    viewerResize(viewer: any): void;
    clearAnnotations(): void;
    getAnnotationsForCurrentImages(): AnnotationGroup[];
    getAnnotationRectsForCurrentImages(): AnnotationRect[];
    updateVisibleAnnotationRects(): void;
    getAnnotationRectIndex(annotationRect: AnnotationRect): number;
    isZoomToSearchResultEnabled(): boolean;
    shouldZoomToInitialAnnotation(): boolean;
    prevAnnotation(): void;
    nextAnnotation(): void;
    getAnnotationRectByIndex(index: number): AnnotationRect | null;
    getInitialAnnotationRect(): AnnotationRect | null;
    zoomToAnnotation(annotationRect: AnnotationRect): void;
    highlightAnnotationRect(annotationRect: AnnotationRect): void;
    getAnnotationOverlayRects(annotationGroup: AnnotationGroup): AnnotationOverlayRect[];
    resize(): void;
    setFocus(): void;
    setNavigatorVisible(): void;
    getControlsFadeLength(): number;
    indicesIncludeChoices(indices: number[]): boolean;
    updateChoiceSwitchVisibility(): void;
}
export {};
